set_property SRC_FILE_INFO {cfile:f:/DuAnCaNhan/fpga/hello_world/hello_world.gen/sources_1/bd/myPSdesign/ip/myPSdesign_processing_system7_0_0/myPSdesign_processing_system7_0_0.xdc rfile:../../../hello_world.gen/sources_1/bd/myPSdesign/ip/myPSdesign_processing_system7_0_0/myPSdesign_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:myPSdesign_i/processing_system7_0/inst} [current_design]
current_instance myPSdesign_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
