# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/myPSdesign/myPSdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myPSdesign || ORIG_REF_NAME==myPSdesign} -quiet] -quiet

# IP: bd/myPSdesign/ip/myPSdesign_processing_system7_0_0/myPSdesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myPSdesign_processing_system7_0_0 || ORIG_REF_NAME==myPSdesign_processing_system7_0_0} -quiet] -quiet

# XDC: f:/DuAnCaNhan/fpga/hello_world/hello_world.gen/sources_1/bd/myPSdesign/ip/myPSdesign_processing_system7_0_0/myPSdesign_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPSdesign_processing_system7_0_0 || ORIG_REF_NAME==myPSdesign_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/DuAnCaNhan/fpga/hello_world/hello_world.gen/sources_1/bd/myPSdesign/myPSdesign_ooc.xdc
